name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build-docker-image:

    runs-on: ubuntu-latest

    steps:

      # download our git repository to our current environment
      # view: https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # view: https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      
      # view: https://github.com/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # view: https://github.com/docker/build-push-action
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: docker-stuff/Dockerfile
          push: true
          tags: avfelipe/app:latest